### ISSUE TITLE
Bug related to empty spaces

### ISSUE THREAD

**Issue by Guillaume-Garrigos** [j2kun/tex-convert-delimiters#1]
Hi! First of all, thanks for this script, it is a great idea and happens to be very useful to me!

One annoying thing though, is that the script crashes when there are *single* spaces in the string. For instance:
`"$e^x$"` or `"$e^x$  "` or `"  $e^x$"` are parsed perfectly (see the double space around the math mode), but
`" $e^x$"` or `"$e^x$ "` return an error : `AttributeError: 'Token' object has no attribute 'data'` at the line `if node.data == "content":`

I am able to debug Python code, but I must recognize that I am completely unable to understand lark syntax. Could it be that you see where is the problem here?

Thanks in advance!

**Comment by j2kun** [comment]
What a strange little bug! It turns out it has nothing to do with the parser definition, but instead has to do with my limited handling of the parsed result.

commit 90a8ba511e8eac34abc7248867e24e0e8d9ccbf2 adds the fix, and it should work for your example now.

**Comment by Guillaume-Garrigos** [comment]
Thank you very much!
