### ISSUE TITLE
$-sign generates an error

### ISSUE THREAD

**Issue by pauloney** [j2kun/tex-convert-delimiters#3]
The simple inclusion of a \$ in the sources to generate a $-sign in the text, as in:

````
\documentclass{minimal}
\begin{document}

This is a dollar-sign: \$.

\end{document}
````

gives:

````
python3 convert-delimiters.py < t.tex > out.tex
Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 126, in feed_token
    action, arg = states[state][token.type]
KeyError: '$END'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
````

There is an obvious solution to make the script work which would be changing all occurrences of ````\$```` to for example ````両両両```` apply the script and then change it back, but what I am really after is a solution within Lark, that would be more robust.

**Comment by j2kun** [comment]
This was left as an exercise to the reader in the article. I imagine a good solution would be to use the priority mechanism to define `\$` as a terminal with higher priority than `$`.

**Comment by pauloney** [comment]
I thought the exercise was for a REGEX and not for the Parser.... but Icould be wrong ...

Paulo Ney
